### ISSUE TITLE
Master mode version: `ReaBlink_Monitor.lua`

### ISSUE THREAD

**Issue by tkna91** [ak5k/reablink#10]
You suggested a master mode here.
https://github.com/ak5k/reablink/issues/9#issuecomment-2211814030

>  If you're planning to use only one instance of REAPER in your Link session, you might want to consider running ReaBlink in Master mode. This can be achieved by editing the ReaBlink_Monitor.lua file and uncommenting line containing reaper.Blink_SetMaster(true).

I was wondering if you could release that as a master mode script so it would be easier for users to keep up with script upgrades.
What do you think?

**Comment by ak5k** [comment]
Master mode isn't exactly Ableton Link standard compliant, as it enforces Ableton Link session timeline to conform to REAPER timing. So it shouldn't be the default behaviour.  However, you can make a copy of ReaBlink_Monitor script, rename it, and use it instead. Then updating will not overwrite it.

**Comment by tkna91** [comment]
Understood. Thanks!
