### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by chausch** [ak5k/reablink#3]
hi there, thanks for this great script! is there a chance for an updated version? the current one tends to crash sometimes on remote stop of transport! thank you!!

**Comment by ak5k** [comment]
Hi! Unfortunately no, or not soon at least. I'm aware of the problem, but currently I don't think a real solid solution (with reasonable amount of work) is possible. If you have really specific use case, you can try writing your own implementation with ReaBlink API calls.

**Comment by chausch** [comment]
oh ok 😞

**Comment by ak5k** [comment]
> oh ok 😞

https://github.com/ak5k/reablink/releases/tag/v0.4.5

Maybe this is more stable?

**Comment by chausch** [comment]
> > oh ok 😞
> 
> https://github.com/ak5k/reablink/releases/tag/v0.4.5
> 
> Maybe this is more stable?

wow, thanks so much! it seeeeems the crashes have stopped. at least they do not occur with local link clients on my machine (m1max, mac os 13.4.1 (22F82), reaper 6.81.0_8adbe74u). will test tomorrow with another person running link in the wireless network. this was the main reason for crashes before. will report back asap! THANK YOU!

**Comment by ak5k** [comment]
> wow, thanks so much! it seeeeems the crashes have stopped. at least they do not occur with local link clients on my machine (m1max, mac os 13.4.1 (22F82), reaper 6.81.0_8adbe74u). will test tomorrow with another person running link in the wireless network. this was the main reason for crashes before. will report back asap! THANK YOU!

Ok, nice. Stopping related crashing should now be solved regardless of platform or connection type.
