### ISSUE TITLE
Playrate unstable

### ISSUE THREAD

**Issue by giohappy** [ak5k/reablink#4]
Is the continous wiggling of the playrate when Link is enabled expected?

![reablink_playrate](https://github.com/ak5k/reablink/assets/571129/3b6619ff-38dd-42b6-8d2d-71bd795b03ec)

- Windows 11
- Reaper v6.82 
- Reablink 0.4.6

**Comment by ak5k** [comment]
I would recommend running the `ReaBlink Monitor` action/script to enable ReaBlink. ReaBlink (in Puppet mode) uses Playrate to try to maintain sync. If you have only one REAPER in Link Session, you could try running ReaBlink in Master mode. There might be some older related discussion in the [forum thread](https://forum.cockos.com/showthread.php?t=254027). A reminder, that my 'built-in' Puppet Mode is somewhat experimental, so extensive testing is recommended in any case.

**Comment by giohappy** [comment]
ok, setting it as master solved the Reaper side but it made the other VCV Rack 2 peer fluctuate.

I've never had problems with Link on my pc (eg with Ableton or Bitwig).Maybe it's Vcv module's fault. I will install Bitwig demo to test against it.

PS I've modified the Monitor script to show wether it's running as master or not.

**Comment by ak5k** [comment]
Ok. Problem is probably with ReaBlink, but it's hard to say. You could try testing, if you can get two instances of REAPER running in sync (only one Master) with ReaBlink. This should work, and be easily achieved. If not, then problem is probably with computer performance/settings.
