### ISSUE TITLE
Run on OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by wckrw** [ak5k/reablink#7]
Is there any chance to run this on OSX 10.11 ?
i see this error when starting monitor
`ReaBlink_Monitor.lua:6: attempt to call a nil value (field 'Blink_GetEnabled')`
and this is in Console on Reaper start
```
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: GetWindowTextLength
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: ListView_GetColumn
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: TreeView_EnsureVisible
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: TreeView_GetParent
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: GetGlyphIndicesW
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: SWELL_ExtendedAPI
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: SWELL_EnableMetal
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: SWELL_osx_is_dark_mode
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: SWELL_ChooseColor
5/2/24 11:19:33,876 REAPER[6871]: SWELL API not found: SWELL_ChooseFont
5/2/24 11:19:33,877 REAPER[6871]: SWELL API not found: IsWindowEnabled
5/2/24 11:19:33,877 REAPER[6871]: SWELL API not found: GetClassName
5/2/24 11:19:33,877 REAPER[6871]: SWELL API not found: SWELL_SetClassName
5/2/24 11:19:33,877 REAPER[6871]: SWELL API not found: SWELL_DisableContextMenu
5/2/24 11:19:33,877 REAPER[6871]: SWELL API not found: EnumDisplayMonitors
5/2/24 11:19:33,877 REAPER[6871]: SWELL API not found: GetMonitorInfo
```

**Comment by ak5k** [comment]
does this work?

https://ci.appveyor.com/api/buildjobs/fg7swpdueh7a83ha/artifacts/build%2Freaper_reablink-x86_64.dylib

**Comment by wckrw** [comment]
no same errors :(
and im actually looking for 32bit (because of old VST looper)
but i tested also on Reaper64 and errors are the same

**Comment by ak5k** [comment]
> no same errors :( and im actually looking for 32bit (because of old VST looper) but i tested also on Reaper64 and errors are the same

https://ci.appveyor.com/api/buildjobs/cdhkec90lqi3sc91/artifacts/build%2Freaper_reablink-i386.dylib

how about this? 32-bit.

**Comment by wckrw** [comment]
still same errors :(
but thanks for your fast help

**Comment by ak5k** [comment]
> still same errors :( but thanks for your fast help

https://ci.appveyor.com/api/buildjobs/743hnfbje1wp45b2/artifacts/build%2Freaper_reablink-i386.dylib

and this? :)

**Comment by wckrw** [comment]
same :(

**Comment by ak5k** [comment]
> same :(

https://ci.appveyor.com/api/buildjobs/775mp43cyob33l4h/artifacts/build%2Freaper_reablink-i386.dylib

How about this? Which REAPER version you're using? The issue probably is that current builds of ReaBlink requires quite recent version of REAPER. However, this version should be compatible with REAPER 5.26 or later.

SWELL API messages are also likely unrelated, and can be ignored. Even if you see the messages on console, try testing the monitor script anyways.

**Comment by wckrw** [comment]
yes, that was it  (using 5.31)
thanks a lot :)

**Comment by ak5k** [comment]
> yes, that was it (using 5.31) thanks a lot :)

Ok great if it loads up. I have no idea how it will perform, and probably can't do anything about it. :)
