### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by tkna91** [ak5k/reablink#9]
I would like to try reablink as I have found that this is available on my OS.
https://github.com/ableton/link

However, it seems to be unable to start with the following error.
```
ReaBlink_Monitor.lua:6: attempt to call a nil value (field 'Blink_GetEnabled')
```
Screencast: 

https://github.com/ak5k/reablink/assets/102382754/7c37ec6c-188d-4a98-b192-2eeed7a993d4

What should I do?

Environment:
- ReaBlink 0.5.6
- reaper 7.17-1
- abletonlink 3.1.2-1
- OS: Arch Linux x86_64
- Kernel: 6.9.7-arch1-1
- WM: sway

**Comment by ak5k** [comment]
It seems the ReaBlink extension itself isn't loaded during REAPER startup. Consider installing ReaBlink through ReaPack and restart REAPER, or make sure you've installed proper version of ReaBlink in correct path for your CPU architecture and operating system. That being said, ReaBlink hasn't been tested on Arch Linux.

E: In this case, https://github.com/ak5k/reablink/releases/download/0.5.6/reaper_reablink-x86_64.so file should be installed into UserPlugins directory under your REAPER resource path.

**Comment by tkna91** [comment]
I restarted REAPER and it seems to have worked! Thanks!

https://github.com/ak5k/reablink/assets/102382754/5a969878-ac63-4464-a378-da8cfce47075

**Comment by ak5k** [comment]
> I restarted REAPER and it seems to have worked! Thanks!
> 
>  20240707-005631_screencast-audioin.mp4

Nice! If you're planning to use only one instance of REAPER in your Link session, you might want to consider running ReaBlink in Master mode. This can be achieved by editing the `ReaBlink_Monitor.lua` file and uncommenting line containing `reaper.Blink_SetMaster(true)`.

**Comment by tkna91** [comment]
Understood. Thanks for the advice!
